### ISSUE TITLE
使用不了了

### ISSUE THREAD

**Issue by shinsbo** [iikira/Baidu-Login#5]
提示错误“发送错误：0”

**Comment by SwJay** [comment]
同样有弹窗提示“发送错误：0”，panic报错如下：

```
2019/05/14 17:14:26 http: panic serving 127.0.0.1:51106: indent can only be space
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc4200a9720)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x7e27e0, 0x8d9cc0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/json-iterator/go.(*frozenConfig).MarshalIndent(0xc4201a0000, 0x7c7480, 0xc42000c758, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_config.go:238 +0x174
github.com/json-iterator/go.MarshalIndent(0x7c7480, 0xc42000c758, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0xc42002c52a, 0x0, 0xc42017f6c0, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_adapter.go:48 +0x81
github.com/iikira/Baidu-Login.execBaiduLogin(0x8e0a60, 0xc4201801c0, 0xc420200400)
	/Users/apple/go/src/github.com/iikira/Baidu-Login/http_server.go:85 +0x2ff
net/http.HandlerFunc.ServeHTTP(0x8a71e8, 0x8e0a60, 0xc4201801c0, 0xc420200400)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xaf1ca0, 0x8e0a60, 0xc4201801c0, 0xc420200400)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42017f380, 0x8e0a60, 0xc4201801c0, 0xc420200400)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200a9720, 0x8e0ee0, 0xc4201cc040)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
2019/05/14 17:14:27 http: panic serving 127.0.0.1:51126: indent can only be space
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc4201f61e0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x7e27e0, 0x8d9cc0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/json-iterator/go.(*frozenConfig).MarshalIndent(0xc4201a0000, 0x7c7480, 0xc4201ae0d8, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_config.go:238 +0x174
github.com/json-iterator/go.MarshalIndent(0x7c7480, 0xc4201ae0d8, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0xc4201ec64a, 0x0, 0xc4201f88f0, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_adapter.go:48 +0x81
github.com/iikira/Baidu-Login.execBaiduLogin(0x8e0a60, 0xc4201f00e0, 0xc420200500)
	/Users/apple/go/src/github.com/iikira/Baidu-Login/http_server.go:85 +0x2ff
net/http.HandlerFunc.ServeHTTP(0x8a71e8, 0x8e0a60, 0xc4201f00e0, 0xc420200500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xaf1ca0, 0x8e0a60, 0xc4201f00e0, 0xc420200500)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42017f380, 0x8e0a60, 0xc4201f00e0, 0xc420200500)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201f61e0, 0x8e0ee0, 0xc4201ea600)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```
