### ISSUE TITLE
Linux使用报错indent can only be space

### ISSUE THREAD

**Issue by lion187chen** [iikira/Baidu-Login#6]
Release 1.2.1 for Linux amd64
通过Web输入用户名和密码后提示错误如下：
http: panic serving 127.0.0.1:45152: indent can only be space
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc4200b7180)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x7e27e0, 0x8d9cc0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/json-iterator/go.(*frozenConfig).MarshalIndent(0xc4201ae000, 0x7c7480, 0xc4201ba088, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_config.go:238 +0x174
github.com/json-iterator/go.MarshalIndent(0x7c7480, 0xc4201ba088, 0x0, 0x0, 0x88b55a, 0x1, 0x0, 0xc4202890d4, 0x0, 0xc42027c340, ...)
	/Users/apple/go/src/github.com/json-iterator/go/feature_adapter.go:48 +0x81
github.com/iikira/Baidu-Login.execBaiduLogin(0x8e0a60, 0xc4202ae620, 0xc4202b2e00)
	/Users/apple/go/src/github.com/iikira/Baidu-Login/http_server.go:85 +0x2ff
net/http.HandlerFunc.ServeHTTP(0x8a71e8, 0x8e0a60, 0xc4202ae620, 0xc4202b2e00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xaf1ca0, 0x8e0a60, 0xc4202ae620, 0xc4202b2e00)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42018d790, 0x8e0a60, 0xc4202ae620, 0xc4202b2e00)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200b7180, 0x8e0ee0, 0xc4201d4040)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

**Comment by wrb233** [comment]
大佬，现在这个还能用吗？？——2021.12.03
